### ISSUE TITLE
usage in an angular service

### ISSUE THREAD

**Issue by ryanper** [adriancarriger/angularfire2-offline#13]
I am trying to use this in a service with the following code 

>import { AngularFire, FirebaseObjectObservable } from 'angularfire2';
import { AngularFireOffline, AfoListObservable, AfoObjectObservable } from 'angularfire2-offline';
@Injectable()
export class UserService {
   user: AfoObjectObservable<any>;
   constructor( public af: AngularFire, public afo: AngularFireOffline ) { }
}

I do not fully understand the DI mechanism, but I get the following error when I inject AngularFireOffline in the constructor.

**I am using the following build tools.**

> @angular/cli: 1.0.0-beta.32.3
node: 6.9.2
os: linux x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9

**My app setup**
>_The main component app.component loads the connect component in my routes like this._
const appRoutes: Routes = [
  { path: 'connect', loadChildren : './connect/connect.module#ConnectModule' },
  { path: '**', redirectTo: '' }
];

>_The connect module which is lazy loaded above looks like this_
import { UserService } from '../user.service';
@NgModule({
  imports: [    
    CommonModule,
    connectRouting,
    MaterialModule,
    FormsModule
  ],
  declarations: [],
  providers: [UserService]
})
export class ConnectModule { }`

>_The connect component is injecting the **UserService** like this_
import { Component, OnInit } from '@angular/core';
import { AngularFire, AuthProviders, AuthMethods } from 'angularfire2';
import { UserService } from '../user.service';
import { User } from '../user';
@Component({
  selector: 'app-connect',
  templateUrl: './connect.component.html',
  styleUrls: ['./connect.component.css']
})
export class ConnectComponent implements OnInit {
  signIn = true;
  email;
  password;
  constructor(public af:AngularFire, public userSrv: UserService) { }

>_The user service is injecting AngularFireOffline in the constructor
import { Injectable } from '@angular/core';
import { User } from './user';
import { AngularFire, FirebaseObjectObservable } from 'angularfire2';
import { AngularFireOffline, AfoListObservable, AfoObjectObservable } from 'angularfire2-offline';
@Injectable()
export class UserService {
  user2: AfoObjectObservable<any>;
  user: FirebaseObjectObservable<any>;
  constructor( public af: AngularFire , public afo: AngularFireOffline) { }

**I am trying to inject and use AngularFireOffline in a similar way to AngularFire**

**Here is the full error dump**

>EXCEPTION: Uncaught (in promise): Error: DI Error
Error: DI Error
    at e.y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:480:508)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:228)
    at new e (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:555)
    at t._throwOrNull (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2766)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3104)
    at t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)
    at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)
    at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)
    at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)
    at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)
t.handleError @ vendor.46e1301….bundle.js:692
next @ vendor.46e1301….bundle.js:288
e.object.i @ vendor.46e1301….bundle.js:699
e.__tryOrUnsub @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:29
e._next @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:8
e.emit @ vendor.46e1301….bundle.js:699
t.triggerError @ vendor.46e1301….bundle.js:57
onHandleError @ vendor.46e1301….bundle.js:57
t.handleError @ polyfills.6c44b7a….bundle.js:36
n.runGuarded @ polyfills.6c44b7a….bundle.js:36
r @ polyfills.6c44b7a….bundle.js:36
a @ polyfills.6c44b7a….bundle.js:36
vendor.46e1301….bundle.js:692 ORIGINAL STACKTRACE:
t.handleError @ vendor.46e1301….bundle.js:692
next @ vendor.46e1301….bundle.js:288
e.object.i @ vendor.46e1301….bundle.js:699
e.__tryOrUnsub @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:29
e._next @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:8
e.emit @ vendor.46e1301….bundle.js:699
t.triggerError @ vendor.46e1301….bundle.js:57
onHandleError @ vendor.46e1301….bundle.js:57
t.handleError @ polyfills.6c44b7a….bundle.js:36
n.runGuarded @ polyfills.6c44b7a….bundle.js:36
r @ polyfills.6c44b7a….bundle.js:36
a @ polyfills.6c44b7a….bundle.js:36
vendor.46e1301….bundle.js:692 Error: Uncaught (in promise): Error: DI Error
Error: DI Error
    at e.y (polyfills.6c44b7a….bundle.js:36)
    at e [as constructor] (vendor.46e1301….bundle.js:480)
    at e [as constructor] (vendor.46e1301….bundle.js:923)
    at new e (vendor.46e1301….bundle.js:923)
    at t._throwOrNull (vendor.46e1301….bundle.js:1224)
    at t._getByKeyDefault (vendor.46e1301….bundle.js:1224)
    at t._getByKey (vendor.46e1301….bundle.js:1224)
    at t.get (vendor.46e1301….bundle.js:1224)
    at e.get (vendor.46e1301….bundle.js:78)
    at e.t.injectorGet (vendor.46e1301….bundle.js:71)
    at e.get (vendor.46e1301….bundle.js:1231)
    at e.get [as _UserService_66] (0.c7c3c44….chunk.js:1)
    at e.getInternal (0.c7c3c44….chunk.js:1)
    at e.get (vendor.46e1301….bundle.js:78)
    at t._getByKeyDefault (vendor.46e1301….bundle.js:1224)
    at y (polyfills.6c44b7a….bundle.js:36)
    at l (polyfills.6c44b7a….bundle.js:36)
    at l (polyfills.6c44b7a….bundle.js:36)
    at polyfills.6c44b7a….bundle.js:36
    at t.invokeTask (polyfills.6c44b7a….bundle.js:36)
    at Object.onInvokeTask (vendor.46e1301….bundle.js:57)
    at t.invokeTask (polyfills.6c44b7a….bundle.js:36)
    at n.runTask (polyfills.6c44b7a….bundle.js:36)
    at a (polyfills.6c44b7a….bundle.js:36)
t.handleError @ vendor.46e1301….bundle.js:692
next @ vendor.46e1301….bundle.js:288
e.object.i @ vendor.46e1301….bundle.js:699
e.__tryOrUnsub @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:29
e._next @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:29
e.next @ vendor.46e1301….bundle.js:8
e.emit @ vendor.46e1301….bundle.js:699
t.triggerError @ vendor.46e1301….bundle.js:57
onHandleError @ vendor.46e1301….bundle.js:57
t.handleError @ polyfills.6c44b7a….bundle.js:36
n.runGuarded @ polyfills.6c44b7a….bundle.js:36
r @ polyfills.6c44b7a….bundle.js:36
a @ polyfills.6c44b7a….bundle.js:36
polyfills.6c44b7a….bundle.js:36 Unhandled Promise rejection: No provider for t! ; Zone: angular ; Task: Promise.then ; Value: e__zone_symbol__currentTask: t__zone_symbol__error: Error: DI Error
    at e.y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:480:508)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:228)
    at new e (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:555)
    at t._throwOrNull (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2766)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3104)
    at t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)
    at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)
    at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)
    at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)
    at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)__zone_symbol__message: "No provider for t!"__zone_symbol__stack: "Error: DI Error↵    at e.y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)↵    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:480:508)↵    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:228)↵    at new e (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:555)↵    at t._throwOrNull (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2766)↵    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3104)↵    at t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)↵    at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)↵    at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)↵    at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)↵    at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)↵    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)"_nativeError: yconstructResolvingMessage: (t)injectors: Array[1]keys: Array[1]message: (...)name: (...)originalStack: (...)stack: (...)toSource: ()toString: ()zoneAwareStack: (...)get message: ()set message: (t)get name: ()set name: (t)get originalStack: ()set originalStack: (t)get stack: ()set stack: (t)get zoneAwareStack: ()set zoneAwareStack: (t)__proto__: e Error: DI Error
    at e.y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:480:508)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:228)
    at new e (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:555)
    at t._throwOrNull (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2766)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3104)
    at t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)
    at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)
    at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)
    at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)
    at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)
o @ polyfills.6c44b7a….bundle.js:36
i @ polyfills.6c44b7a….bundle.js:36
r @ polyfills.6c44b7a….bundle.js:36
a @ polyfills.6c44b7a….bundle.js:36
polyfills.6c44b7a….bundle.js:36 y__zone_symbol__error: Error: Uncaught (in promise): Error: DI Error
Error: DI Error
    at e.y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:480:508)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:228)
    at new e (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:555)
    at t._throwOrNull (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2766)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3104)
    at t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)
    at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)
    at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)
    at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)
    at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)
    at e.y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:480:508)
    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:228)
    at new e (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:555)
    at t._throwOrNull (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2766)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3104)
    at t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)
    at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)
    at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)
    at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)
    at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)
    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)
    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)
    at y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)
    at l (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:1605)
    at l (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:1291)
    at https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2119
    at t.invokeTask (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:10021)
    at Object.onInvokeTask (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:57:2559)
    at t.invokeTask (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:9942)
    at n.runTask (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:5710)
    at a (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:667)__zone_symbol__message: "Uncaught (in promise): Error: DI Error↵Error: DI Error↵    at e.y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)↵    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:480:508)↵    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:228)↵    at new e (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:555)↵    at t._throwOrNull (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2766)↵    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3104)↵    at t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)↵    at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)↵    at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)↵    at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)↵    at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)↵    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)"__zone_symbol__stack: "Error: Uncaught (in promise): Error: DI Error↵Error: DI Error↵    at e.y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)↵    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:480:508)↵    at e [as constructor] (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:228)↵    at new e (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:923:555)↵    at t._throwOrNull (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2766)↵    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3104)↵    at t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)↵    at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)↵    at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)↵    at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)↵    at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)↵    at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)↵    at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)↵    at y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)↵    at l (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:1605)↵    at l (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:1291)↵    at https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2119↵    at t.invokeTask (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:10021)↵    at Object.onInvokeTask (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:57:2559)↵    at t.invokeTask (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:9942)↵    at n.runTask (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:5710)↵    at a (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:667)"message: (...)name: (...)originalStack: (...)promise: trejection: estack: (...)task: ttoSource: ()toString: ()zone: nzoneAwareStack: (...)get message: ()set message: (t)get name: ()set name: (t)get originalStack: ()set originalStack: (t)get stack: ()set stack: (t)get zoneAwareStack: ()set zoneAwareStack: (t)__proto__: Object
o @ polyfills.6c44b7a….bundle.js:36
i @ polyfills.6c44b7a….bundle.js:36
r @ polyfills.6c44b7a….bundle.js:36
a @ polyfills.6c44b7a….bundle.js:36

**Comment by adriancarriger** [comment]
Hi @ryanper 

I think it would help if you can copy and paste the entire error you're getting. Thanks!

**Comment by ryanper** [comment]
Hi @adriancarriger  sorry I did not leave the full error earlier, I have updated the original comment with the full error and added more details as well.

**Comment by DennisSmolek** [comment]
The core of your error is the "No Provider For t!" This comes from not having a provider for one or more of your services. 
My guess is you aren't including the `AngularFireOfflineModule` in your main `ngModule`.

Checkout the [install instructions for the ngModule](https://github.com/adriancarriger/angularfire2-offline#setup-ngmodule)

When you try to inject the service (and it looks like it's  minified) it doesn't know what it is and throws the error. 

Also, on Github when you do code use the \` symbol before and after code if you want it inline: `likeThis()`

and when you paste larger portions, enter a line break, then use three in a row: \``` then line break, then three again \```

``` javascript
// BONUS if you add  a space then 'javascript' like: ``` javascript 
// it does syntax highlighting!
export class whatever extends whatever {
    public: super = cool;
    constructor(public af: AngularFire) {
    }
}
```

it makes it WAY easier to read, checkout your error log now:

```
t._getByKey (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:2485)
 at t.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:848)
 at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1137)
 at e.t.injectorGet (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:71:1750)
 at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1231:350)
 at e.get [as _UserService_66] (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:7030)
 at e.getInternal (https://lxcvm1.com:4200/0.c7c3c44ecf998a6e0ba8.chunk.js:1:10958)
 at e.get (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:78:1095)
 at t._getByKeyDefault (https://lxcvm1.com:4200/vendor.46e1301094688acb945c.bundle.js:1224:3084)
 at y (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2553)
 at l (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:1605)
 at l (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:1291)
 at https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:2119
 at t.invokeTask (https://lxcvm1.com:4200/polyfills.6c44b7ae36503ab61f4d.bundle.js:36:10021)
 at Object.onInvokeTask 
```

**Comment by adriancarriger** [comment]
Thanks @DennisSmolek! Yes, this sounds like you need to provide the module. If that does not solve your issue just let me know and I'll reopen the issue. Thanks!

**Comment by ryanper** [comment]
Thank you so much @DennisSmolek, not sure what I was thinking. I am loading AngularFireOfflineModule in a sub module and not in the main root module and it works, also thanks for the tips on inserting code I shall read markdown more thoroughly.
